### ISSUE TITLE
Code is broken when cuda is NOT used

### ISSUE THREAD

**Issue by jmichaux** [roahmlab/armour-dev#4]
I was trying to debug the collisions by plotting the FO. However, I noticed that when I set the `use_cuda_flag`to `false`, that the code was broken. I'm not sure to what extent. But I noticed that the sliced FO are empty and the optimization is returning NaNs.

https://github.com/roahmlab/armour-dev/blob/9f23e70105563c0cd9b23270142158f58aa12436/kinova_src/kinova_simulator_interfaces/uarmtd_planner.m#L380

**Comment by Cfather** [comment]
The code is unfortunately not fully tested for pure matlab planner and controller
