### ISSUE TITLE
Transmission inertia breaks MATLAB robust controller

### ISSUE THREAD

**Issue by pdholmes** [roahmlab/armour-dev#5]
The inclusion of the transmission inertia in `uarmtd_agent` https://github.com/roahmlab/armour-dev/blob/main/kinova_src/kinova_simulator_interfaces/uarmtd_agent.m#L370 isn't accounted for in MATLAB's robust input or in the planner. I think `rnea.m`, `interval_rnea.m`, and `poly_zonotope_rnea.m` should be updated to account for transmission inertia if we want to include it.

**Comment by Cfather** [comment]
fixed
