### ISSUE TITLE
should we make the ultimate bound the default?

### ISSUE THREAD

**Issue by jmichaux** [roahmlab/armour-dev#6]
https://github.com/roahmlab/armour-dev/blob/695a1cde7daf4e8c4d33c5b10e256c9ae9b060b6/kinova_src/kinova_simulator_interfaces/polynomial_zonotope_matlab/create_jrs_online.m#L16

**Comment by Cfather** [comment]
Users should be able to choose their own controller parameter and get any desired ultimate bound.
